version: "3"

services:

  blood-oxygen-level-service:
    container_name: blood-oxygen-levels
    build:
      context: ./Docker/BOL/
      dockerfile: Dockerfile
    image: blood-oxygen-levels:latest
    restart: always
    depends_on:
      - mqtt
    networks:
      sleep-monitor-network:
        ipv4_address: ${BLOOD_OXYGEN_LEVELS_IP}

  body-temperature-service:
    container_name: body-temperature
    build:
      context: ./Docker/BT/
      dockerfile: Dockerfile
    image: body-temperature:latest
    restart: always
    depends_on:
      - mqtt
    networks:
      sleep-monitor-network:
        ipv4_address: ${BODY_TEMPERATURE_IP}

  eye-movement-service:
    container_name: eye-movement
    build:
      context: ./Docker/EM/
      dockerfile: Dockerfile
    image: eye-movement:latest
    restart: always
    depends_on:
      - mqtt
    networks:
      sleep-monitor-network:
        ipv4_address: ${EYE_MOVEMENT_IP}

  hours-of-sleep-service:
    container_name: hours-of-sleep
    build:
      context: ./Docker/HOS/
      dockerfile: Dockerfile
    image: hours-of-sleep:latest
    restart: always
    depends_on:
      - mqtt
    networks:
      sleep-monitor-network:
        ipv4_address: ${HOURS_OF_SLEEP_IP}

  heart-rate-service:
    container_name: heart-rate
    build:
      context: ./Docker/HR/
      dockerfile: Dockerfile
    image: heart-rate:latest
    restart: always
    depends_on:
      - mqtt
    networks:
      sleep-monitor-network:
        ipv4_address: ${HEART_RATE_IP}

  limb-movement-rate-service:
    container_name: limb-movement-rate
    build:
      context: ./Docker/LMR/
      dockerfile: Dockerfile
    image: limb-movement-rate:latest
    restart: always
    depends_on:
      - mqtt
    networks:
      sleep-monitor-network:
        ipv4_address: ${LIMB_MOVEMENT_RATE_IP}

  respiration-rate-service:
    container_name: respiration-rate
    build:
      context: ./Docker/RR/
      dockerfile: Dockerfile
    image: respiration-rate:latest
    restart: always
    depends_on:
      - mqtt
    networks:
      sleep-monitor-network:
        ipv4_address: ${RESPIRATION_RATE_IP}

  stress-levels-service:
    container_name: stress-levels
    build:
      context: ./Docker/SL/
      dockerfile: Dockerfile
    image: stress-levels:latest
    restart: always
    depends_on:
      - mqtt
    networks:
      sleep-monitor-network:
        ipv4_address: ${SRESS_LEVELS_IP}

  snoring-range-service:
    container_name: snoring-range
    build:
      context: ./Docker/SR/
      dockerfile: Dockerfile
    image: snoring-range:latest
    restart: always
    depends_on:
      - mqtt
    networks:
      sleep-monitor-network:
        ipv4_address: ${SNORING_RANGE_IP}

  node-red:
    restart: always
    depends_on:
      - mqtt
    image: nodered/node-red
    container_name: sleep-monitor-nodered-1
    build: docker-nodered/
    ports:
      - 1880:1880
    networks:
      sleep-monitor-network:
        ipv4_address: ${NODE_RED_IP}
    volumes: 
      - ./nodered/data:/data

  mqtt:
      image: toke/mosquitto
      container_name: mqtt
      expose:
        - 1883
      ports:
        - 1883:1883
      restart: unless-stopped
      networks:
        sleep-monitor-network:
          ipv4_address: ${MQTT_IP}

  influxdb:
    image: influxdb:2.7.4
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    networks:
      sleep-monitor-network:
        ipv4_address: ${INFLUXDB_IP}

  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
      - mqtt
    networks:
      sleep-monitor-network:
        ipv4_address: ${TELEGRAF_IP}

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - ./grafana:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      sleep-monitor-network:
        ipv4_address: ${GRAFANA_IP}

volumes:
  grafana-storage:
  influxdb-storage:

networks:
  sleep-monitor-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
